# ===============================================
#   SFTP Configuration
# ===============================================
sftp.host=sftpusecase.blob.core.windows.net
sftp.username=sftpusecase.upendrathunuguntla

# ===============================================
#   API Manager Details
# ===============================================
api.id=20412692