# ===============================================
#   SFTP Configuration
# ===============================================
sftp.host=sftpusecase.blob.core.windows.net
sftp.username=sftpusecase.upendrathunuguntla
sftp.path=/retail/inbound
sftp.archive.path=/retail/inbound/archive
# ===============================================
#   API Manager Details
# ===============================================
api.id=20414507